### ISSUE TITLE
icalendar missing in Dockerfile ?

### ISSUE THREAD

**Issue by fguiotte** [AlexandreRio/interprete#27]
`ModuleNotFoundError: No module named 'icalendar' (file "/home/sopel/.sopel/modules/kdoc.py", line 7, in <module>)`

**Comment by AlexandreRio** [comment]
The used image contains `pip`  but not the required dependencies of some modules.
Quick fix: using something similar to `docker exec pip install icalendar`.
Proper fix: creating a new image on the docker hub

**Comment by fguiotte** [comment]
Quick fix fix: `docker-compose -f sopel.yml exec --user root sopel pip install icalendar`

**Comment by AlexandreRio** [comment]
This is fixed in e2833cb765f285b995c5ec47a8a65e0e6795d3ec
